name: revent
description: Revent App.
publish_to: 'none' 

version: 1.0.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  get_it: ^8.0.0
  mysql_client: ^0.0.27
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  flutter_native_image: ^0.0.6+1
  image_picker_plus: ^0.5.9
  intl: ^0.19.0
  dynamic_height_grid_view: ^0.0.4
  flutter_cache_manager: ^3.3.1 
  animated_flip_counter: ^0.3.3
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.2.0
  quick_actions: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/albert_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env