name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      # Optional: Enforce code formatting
      # - name: Check formatting
      #   run: flutter format --set-exit-if-changed .

      # Optional: Build apk/web/etc (good for release pipeline)
      # - name: Build APK
      #   run: flutter build apk --release